name: Auto Build Scanner
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutu
        uses: actions/checkout@master

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK with Gradle
        run: |
          mkdir -p out
          chmod +x gradlew
          ./gradlew assembleRelease
          mv ~/app/build/outputs/apk/release/app-release-unsigned.apk out/app-release.apk
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.zip
          path: out/app-release.apk
