name: Auto Build Scanner Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutu
        uses: actions/checkout@master

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: gen JKS File
        run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      - name: Build APK with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: ${{ github.sha }}

      - name: Upload Released APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
